/**
 * Blog Engine - Dynamic Blog Post Rendering System
 * Fetches blog posts from JSON files and renders them dynamically
 */

class BlogEngine {
  constructor() {
    this.posts = [];
    this.filteredPosts = [];
    this.currentCategory = 'All Articles';
    this.postsPerPage = 9;
    this.currentPage = 1;
    this.blogFolder = './blogs/';
  }

  /**
   * Initialize the blog engine
   */
  async init() {
    await this.loadBlogPosts();
    this.setupEventListeners();
    this.renderBlogPosts();
    this.renderPagination();
  }

  /**
   * Load all blog posts from JSON files
   */
  async loadBlogPosts() {
    try {
      // Load blog index (auto-generated by build script)
      const indexResponse = await fetch('./blogs/blog-index.json');
      if (!indexResponse.ok) {
        throw new Error('Index response was not ok');
      }
      const blogIndex = await indexResponse.json();
      const postFiles = blogIndex.posts || [];

      const promises = postFiles.map(file => 
        fetch(`${this.blogFolder}${file}`)
          .then(response => {
            if (!response.ok) throw new Error('Post not found');
            return response.json();
          })
          .catch(error => {
            console.error(`Error loading ${file}:`, error);
            return null;
          })
      );

      const results = await Promise.all(promises);
      this.posts = results.filter(post => post !== null);
      
      // Sort posts by date (newest first)
      this.posts.sort((a, b) => new Date(b.date) - new Date(a.date));
      this.filteredPosts = [...this.posts];
      
      console.log(`Loaded ${this.posts.length} blog posts`);
    } catch (error) {
      console.error('Error loading blog index:', error);
      this.posts = [];
      this.filteredPosts = [];
    }
  }

  /**
   * Setup event listeners for filters and pagination
   */
  setupEventListeners() {
    // Category filter buttons
    const filterButtons = document.querySelectorAll('.filter-btn');
    filterButtons.forEach(button => {
      button.addEventListener('click', (e) => {
        this.handleCategoryFilter(e.target);
      });
    });
  }

  /**
   * Handle category filtering
   */
  handleCategoryFilter(button) {
    // Update active button
    document.querySelectorAll('.filter-btn').forEach(btn => 
      btn.classList.remove('active')
    );
    button.classList.add('active');

    // Get category from button text
    const category = button.textContent.trim();
    this.currentCategory = category;
    
    // Filter posts
    if (category === 'All Articles') {
      this.filteredPosts = [...this.posts];
    } else {
      this.filteredPosts = this.posts.filter(post => 
        post.category.toLowerCase() === category.toLowerCase()
      );
    }

    // Reset to first page and render
    this.currentPage = 1;
    this.renderBlogPosts();
    this.renderPagination();
  }

  /**
   * Render blog posts to the DOM
   */
  renderBlogPosts() {
    const blogGrid = document.getElementById('blogGrid');
    if (!blogGrid) return;

    // Calculate pagination
    const startIndex = (this.currentPage - 1) * this.postsPerPage;
    const endIndex = startIndex + this.postsPerPage;
    const postsToShow = this.filteredPosts.slice(startIndex, endIndex);

    // Clear existing content
    blogGrid.innerHTML = '';

    // Render each post
    postsToShow.forEach((post, index) => {
      const postCard = this.createBlogCard(post, index === 0 && this.currentPage === 1);
      blogGrid.appendChild(postCard);
    });

    // Show message if no posts
    if (postsToShow.length === 0) {
      blogGrid.innerHTML = '<p style="text-align: center; grid-column: 1 / -1; padding: 5rem 0; color: #666; font-size: 0.95rem;">No blog posts found in this category.</p>';
    }
  }

  /**
   * Create a blog card element
   */
  createBlogCard(post, isFeatured = false) {
    const article = document.createElement('article');
    article.className = 'blog-card';
    if (isFeatured) {
      article.style.gridColumn = 'span 1'; // Keep consistent in hairline layout
    }

    let imageHTML = '';
    if (post.image) {
      const base = post.image.substring(0, post.image.lastIndexOf('.'));
      imageHTML = `
        <div style="width: 100%; height: 220px; overflow: hidden; border-bottom: 1px solid var(--color-border); margin-bottom: 1.5rem; background-color: var(--color-border); position: relative;">
          <picture style="width: 100%; height: 100%; display: block;">
            <source type="image/avif" srcset="./blogs_images/${base}.avif">
            <source type="image/webp" srcset="./blogs_images/${base}.webp">
            <img src="./blogs_images/${post.image}" 
                 alt="${post.title}" 
                 style="width: 100%; height: 100%; object-fit: cover; filter: grayscale(100%); transition: var(--transition-smooth);"
                 class="blog-card-img"
                 loading="lazy"
                 onerror="this.style.display='none'; this.parentNode.style.display='none';">
          </picture>
        </div>
      `;
    }

    article.innerHTML = `
      ${imageHTML}
      <div style="display: flex; flex-direction: column; flex-grow: 1; justify-content: space-between; height: 100%;">
        <div>
          <span class="blog-card-category">${post.category}</span>
          <h3 class="serif-font" style="font-size: 1.35rem; line-height: 1.3; margin-bottom: 1rem; font-weight: 500;">
            <a href="${post.slug}.html">${post.title}</a>
          </h3>
          <p style="font-size: 0.9rem; color: #555555; margin-bottom: 1.5rem; line-height: 1.6;">${post.excerpt}</p>
        </div>
        <div class="blog-card-meta">
          <span>${new Date(post.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</span>
          <span>${post.readTime}</span>
        </div>
      </div>
    `;

    // Add inline hover triggers for the image grayscale filter
    const img = article.querySelector('.blog-card-img');
    if (img) {
      article.addEventListener('mouseenter', () => {
        img.style.filter = 'grayscale(0%)';
        img.style.transform = 'scale(1.03)';
      });
      article.addEventListener('mouseleave', () => {
        img.style.filter = 'grayscale(100%)';
        img.style.transform = 'scale(1)';
      });
    }

    return article;
  }

  /**
   * Render pagination controls
   */
  renderPagination() {
    const paginationContainer = document.getElementById('pagination');
    if (!paginationContainer) return;

    const totalPages = Math.ceil(this.filteredPosts.length / this.postsPerPage);
    
    // Clear existing pagination
    paginationContainer.innerHTML = '';

    // Don't show pagination if only one page
    if (totalPages <= 1) return;

    // Create pagination buttons
    for (let i = 1; i <= totalPages; i++) {
      const button = document.createElement('a');
      button.href = '#';
      button.className = `pagination-btn ${i === this.currentPage ? 'active' : ''}`;
      button.textContent = i;
      button.style.cssText = `
        display: inline-flex;
        align-items: center;
        justify-content: center;
        width: 36px;
        height: 36px;
        border: 1px solid var(--color-border);
        color: var(--color-text-dark);
        font-weight: 500;
        font-size: 0.85rem;
        transition: var(--transition-fast);
        background-color: ${i === this.currentPage ? 'var(--color-text-dark)' : 'transparent'};
        color: ${i === this.currentPage ? 'var(--color-bg-cream)' : 'var(--color-text-dark)'};
      `;

      button.addEventListener('click', (e) => {
        e.preventDefault();
        this.currentPage = i;
        this.renderBlogPosts();
        this.renderPagination();
        window.scrollTo({ top: 0, behavior: 'smooth' });
      });
      paginationContainer.appendChild(button);
    }
  }
}

// Initialize blog engine when DOM is loaded
document.addEventListener('DOMContentLoaded', () => {
  const blogEngine = new BlogEngine();
  blogEngine.init();
});
